# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSToastMessageExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SSToastMessage'

  # Pods for SSToastMessageExample

  target 'SSToastMessageExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SSToastMessageExampleUITests' do
    # Pods for testing
  end

end

target 'SSToastMessageExampleMacOS' do
  pod 'SSToastMessage'
end
